server:
  port: 8082

spring:
  application:
    name: trip-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ride_hailing
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
