server:
  port: 8084

spring:
  application:
    name: rider-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ride_hailing
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
